const { setToken, log } = require("./index");

setToken(
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJhcmthZGlwNjcxQGdtYWlsLmNvbSIsImV4cCI6MTc3ODQ4ODkwNiwiaWF0IjoxNzc4NDg4MDA2LCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiMWMzNzMxZGYtMTNlOC00ZTFlLWIxMDgtYzcwMWUxZTMwN2NjIiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoiYXJrYWRpcCBkYXMiLCJzdWIiOiIzYTM4OGVlMi0yMGE0LTQzZjItOTVhMy1iMTBlMDNmZWE1ZDkifSwiZW1haWwiOiJhcmthZGlwNjcxQGdtYWlsLmNvbSIsIm5hbWUiOiJhcmthZGlwIGRhcyIsInJvbGxObyI6ImUyM2NzZXUwNjU3IiwiYWNjZXNzQ29kZSI6IlRmRHhnciIsImNsaWVudElEIjoiM2EzODhlZTItMjBhNC00M2YyLTk1YTMtYjEwZTAzZmVhNWQ5IiwiY2xpZW50U2VjcmV0IjoiQ0J6YUtjSlNCellyZ1BSQiJ9.D0W5txs1KLme0raVc1ohYJXmV2Atamaf0ycMEUiTbBk",
);

log("backend", "info", "middleware", "server started");
log("frontend", "info", "middleware", "server started");
