const { setToken, log } = require("./index");

setToken(
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJhcmthZGlwNjcxQGdtYWlsLmNvbSIsImV4cCI6MTc3ODQ4NDkzOSwiaWF0IjoxNzc4NDg0MDM5LCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiMjBmYjA1NTctYWMwZC00NGM1LTlmYTctZGM5ZjNkMmFhZDc2IiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoiYXJrYWRpcCBkYXMiLCJzdWIiOiIzYTM4OGVlMi0yMGE0LTQzZjItOTVhMy1iMTBlMDNmZWE1ZDkifSwiZW1haWwiOiJhcmthZGlwNjcxQGdtYWlsLmNvbSIsIm5hbWUiOiJhcmthZGlwIGRhcyIsInJvbGxObyI6ImUyM2NzZXUwNjU3IiwiYWNjZXNzQ29kZSI6IlRmRHhnciIsImNsaWVudElEIjoiM2EzODhlZTItMjBhNC00M2YyLTk1YTMtYjEwZTAzZmVhNWQ5IiwiY2xpZW50U2VjcmV0IjoiQ0J6YUtjSlNCellyZ1BSQiJ9.4jJ_Xqt_tY8Ioknbg-iqkra5tNl8flAZiWxjRuQt8kc",
);

log("backend", "info", "middleware", "server started");
log("frontend", "info", "middleware", "server started");
